### ISSUE TITLE
deploying etcd or cinder not possible due to storage issues

### ISSUE THREAD

**Issue by arif-ali** [juju/terraform-provider-juju#481]
### Description

When deploying etcd or cinder, it is expecting to add storage. However, when deploying these 2 applications in LXD or KVM, this is not possible in juju, and doesn't allow it to go through.

Deploying the same 2 application via the `bundle.yaml` we don't face the same issues at all. We should be able to mimic the old way

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.12.0

### Terraform version

1.8.2

### Juju version

2.9.49

### Terraform Configuration(s)

```terraform
resource "juju_application" "etcd" {
  name = "etcd"

  model = juju_model.cpe-focal.name

  charm {
    name     = "etcd"
    channel  = "latest/stable"
    base     = "ubuntu@20.04"
    revision = 583
  }

  placement = "${join(",",sort([
    juju_machine.etcd-1.machine_id,
    juju_machine.etcd-2.machine_id,
    juju_machine.etcd-3.machine_id,
  ]))}"

  endpoint_bindings = [{
    space = "oam"
  },{
    space = "oam"
    endpoint = "cluster"
  },{
    space = "oam"
    endpoint = "db"
  }]

  units = 3

  config = {
    channel = "3.2/stable"
  }
}
```

### Reproduce / Test

```shell
terraform apply of the above plan gives us the following error


ERROR cannot add application "etcd": cannot deploy to machine 1/lxd/2: adding storage to lxd container not supported
```

Now using the following bundle, we are able to deploy the etcd application

```yaml
applications:
  etcd:
    charm: cs:etcd
    num_units: 3
    bindings:
      "": *oam-space   
      cluster: *internal-space
      db: *internal-space
    options:
      channel: 3.2/stable
    to:
      - lxd:400
      - lxd:401
      - lxd:402
```

### Notes & References

Further analysis shows that, when deploying the above bundle, the following excerpt is from the export-bundle, and shows that we have `storage data=loop,1024M`.

```yaml
  etcd:
    charm: etcd
    channel: latest/stable
    revision: 583
    resources:
      core: 0
      etcd: 3
      snapshot: 0
    num_units: 3
    to:
    - lxd:1
    - lxd:8
    - lxd:9
    options:
      channel: 3.2/stable
    constraints: arch=amd64
    storage:
      data: loop,1024M
    bindings:
      "": oam
      certificates: oam
      cluster: oam
      db: oam
      nrpe-external-master: oam
      proxy: oam
```

Now,i if we run the following command, we get the same error.

```
juju deploy etcd -n 3 --to 1/lxd/2,8/lxd/3,9/lxd/2 --storage data=loop,1024M
```

Ultimately, it would be good to be able to deploy the terraform plan above so, that it can mimic the bundle behaviour
