### ISSUE TITLE
MAAS device error: "device base schema check failed: expected map, got []interfaces {}([]interface {}{})"

### ISSUE THREAD

**Issue by howels** [juju/terraform-provider-juju#783]
### Description

When installing COS on K8S via TF, we get this error in the Juju TF provider, which is shown more fully in the output of `juju status`:

```
    containers:
      0/lxd/0:
        juju-status:
          current: down
          message: agent is not communicating with the server
          since: 30 Jun 2025 15:13:44Z
        instance-id: pending
        machine-status:
          current: provisioning error
          message: 'failed to create MAAS device for "juju-29ad68-0-lxd-0": device
            base schema check failed: expected map, got []interface {}([]interface
            {}{})'
          since: 30 Jun 2025 15:13:44Z
```

This occurs when deploying LXD containers from TF, the LXD container never fully deploys:
```
2/lxd/0  down                   pending    ubuntu@22.04                failed to create MAAS device for "juju-29ad68-2-lxd-0": device base schema check failed: expected map, got []interfac...
```
The MAAS installation has been working outside of TF and we have deployed Landscape on MAAS already.

I have tested `v0.18.0`, `v0.19.0` and `v0.20` on the Juju TF provider with the same results.

Details of the MAAS server (MAAS version 3.5.6):
```
$ for conf in $(maas admin maas get-config --help | awk '/^:[^ ]*:/{print $1}' | tr -d :); do echo "::: $conf" $(maas admin maas get-config name=$conf); done
::: active_discovery_interval 10800
::: auto_vlan_creation true
::: boot_images_auto_import true
::: boot_images_no_proxy false
::: commissioning_distro_series "jammy"
::: completed_intro true
::: curtin_verbose true
::: default_distro_series "jammy"
::: default_dns_ttl 30
::: default_min_hwe_kernel ""
::: default_osystem "ubuntu"
::: default_storage_layout "flat"
::: disk_erase_with_quick_erase false
::: disk_erase_with_secure_erase true
::: dns_trusted_acl null
::: dnssec_validation "no"
::: enable_analytics true
::: enable_disk_erasing_on_release false
::: enable_http_proxy false
::: enable_third_party_drivers true
::: enlist_commissioning false
::: force_v1_network_yaml false
::: hardware_sync_interval "15m"
::: http_proxy ""
::: kernel_opts "console=tty0 console=ttyS0,115200n8"
::: maas_auto_ipmi_cipher_suite_id "3"
::: maas_auto_ipmi_k_g_bmc_key ""
::: maas_auto_ipmi_user "maas"
::: maas_auto_ipmi_user_privilege_level "ADMIN"
::: maas_auto_ipmi_workaround_flags null
::: maas_internal_domain "maas-internal"
::: maas_name "us-westp-1 maas"
::: maas_proxy_port 8000
::: maas_syslog_port 5247
::: max_node_commissioning_results 10
::: max_node_installation_results 3
::: max_node_release_results 3
::: max_node_testing_results 10
::: network_discovery "enabled"
::: node_timeout 30
::: ntp_external_only false
::: ntp_servers "10.2.14.253 10.2.14.254 10.2.14.255"
::: prefer_v4_proxy false
::: prometheus_enabled false
::: prometheus_push_gateway null
::: prometheus_push_interval 60
::: promtail_enabled false
::: promtail_port 5238
::: release_notifications true
::: remote_syslog null
::: session_length 1209600
::: subnet_ip_exhaustion_threshold_count 16
::: theme ""
::: tls_cert_expiration_notification_enabled false
::: tls_cert_expiration_notification_interval 30
::: upstream_dns "10.2.14.171 10.2.14.172"
::: use_peer_proxy false
::: use_rack_proxy true
::: vcenter_datacenter ""
::: vcenter_password ""
::: vcenter_server ""
::: vcenter_username ""
::: windows_kms_host null
```

### Urgency

Casually reporting

### Terraform Juju Provider version

0.20

### Terraform version

OpenTofu v1.10.1

### Juju version

3.6.7

### Terraform Configuration(s)

```terraform
Please refer to the Canonical deployment of COS on K8S shipped as part of Canonical OpenStack - this is part of an official Canonical engagement.
```

### Reproduce / Test

```shell
terraform init
terraform apply -approve
```

### Debug/Panic Output

```shell

```

### Notes & References

We also have to insert numerous manual delays via bash job-control (`CTRL+Z`, check status in juju then `fg` once machine is deployed) because after CIS hardening the Juju provider times out unless manually delayed. This is also clearly undesirable but does not appear directly related to this issue.

**Comment by vernhart** [comment]
We're running MAAS 3.5.6.

In two other (theoretically) identical environments, we are not seeing the same issue. The most obvious differenc is juju versions. The environment that I deployed uses juju 3.6.5 and another that a colleague deployed is 3.6.6. There may be other differences that we don't realize but this one stands out.

**Comment by alesstimec** [comment]
This appears to be a Juju issue. Have you opened an issue on https://github.com/juju/juju/issues

**Comment by manadart** [comment]
You can't downgrade a Juju model.

This are of code has not changed in recent years, and I can not replicate on my MAAS (more recent than this).

To see what we are actually getting back from MAAS do this:
- `juju model-config -m controller logging-config`.
- Reset with `juju model-config -m controller logging-config="<original-config>;maas=TRACE"`.
- Attempt to create a container-on-machine again.

You're looking for a POST to `devices` like this:
```
machine-0: 11:52:05 TRACE maas request 2a: POST http://192.168.30.2:5240/MAAS/api/2.0/devices/, params=hostname=juju-814abc-0-lxd-0&mac_addresses=00%3A16%3A3e%3A7e%3Ac5%3Ab7&parent=84hxfy
machine-0: 11:52:06 TRACE maas response 2a: {
    "tag_names": [],
    "fqdn": "juju-814abc-0-lxd-0.maas",
    "hostname": "juju-814abc-0-lxd-0",
    "owner_data": {},
    "interface_set": [
        {
            "sriov_max_vf": 0,
            "params": {},
            "link_connected": true,
            "numa_node": null,
            "product": null,
            "children": [],
            "parents": [],
            "name": "eth0",
            "interface_speed": 0,
            "links": [],
            "vlan": null,
            "enabled": true,
            "type": "physical",
            "mac_address": "00:16:3e:7e:c5:b7",
            "vendor": null,
            "firmware_version": null,
            "tags": [],
            "effective_mtu": 1500,
            "id": 30,
            "link_speed": 0,
            "system_id": "pdmq68",
            "discovered": null,
            "resource_uri": "/MAAS/api/2.0/nodes/pdmq68/interfaces/30/"
        }
    ],
    "zone": {
        "name": "default",
        "description": "",
        "id": 1,
        "resource_uri": "/MAAS/api/2.0/zones/default/"
    },
    "workload_annotations": {},
    "node_type_name": "Device",
    "system_id": "pdmq68",
    "description": "",
    "parent": "84hxfy",
    "ip_addresses": [],
    "node_type": 1,
    "address_ttl": null,
    "owner": "joseph",
    "domain": {
        "authoritative": true,
        "ttl": null,
        "resource_record_count": 0,
        "is_default": true,
        "name": "maas",
        "id": 0,
        "resource_uri": "/MAAS/api/2.0/domains/0/"
    },
    "resource_uri": "/MAAS/api/2.0/devices/pdmq68/"
}
```

**Comment by manadart** [comment]
Can you also get the output of `juju show-machine <n>` for the one you're trying to add a container to?

**Comment by howels** [comment]
> Can you also get the output of `juju show-machine <n>` for the one you're trying to add a container to?

Here is the host VM and the container in `juju machines`:
```
machines:
  "0":
    juju-status:
      current: started
      since: 30 Jun 2025 15:08:27Z
      version: 3.6.7
    hostname: k8s-cos-3
    dns-name: 10.192.16.65
    ip-addresses:
    - 10.192.16.65
    - 10.192.8.23
    - 10.1.1.82
    instance-id: xpk7tm
    display-name: k8s-cos-3
    machine-status:
      current: running
      message: Deployed
      since: 30 Jun 2025 15:03:31Z
    modification-status:
      current: idle
      since: 30 Jun 2025 14:56:47Z
    base:
      name: ubuntu
      channel: "22.04"
    network-interfaces:
      br-oam:
        ip-addresses:
        - 10.192.8.23
        mac-address: 9e:eb:c0:d9:1f:eb
        gateway: 10.192.8.1
        space: oam-space
        is-up: true
      cilium_host:
        ip-addresses:
        - 10.1.1.82
        mac-address: 5a:d8:17:e5:e9:bb
        is-up: true
      int:
        ip-addresses:
        - 10.192.16.65
        mac-address: 52:54:00:ed:cd:3e
        space: internal-space
        is-up: true
      oam:
        ip-addresses:
        - 10.192.8.23
        mac-address: 52:54:00:c4:3f:60
        gateway: 10.192.8.1
        space: oam-space
        is-up: true
    containers:
      0/lxd/0:
        juju-status:
          current: down
          message: agent is not communicating with the server
          since: 30 Jun 2025 15:13:44Z
        instance-id: pending
        machine-status:
          current: provisioning error
          message: 'failed to create MAAS device for "juju-29ad68-0-lxd-0": device
            base schema check failed: expected map, got []interface {}([]interface
            {}{})'
          since: 30 Jun 2025 15:13:44Z
        modification-status:
          current: idle
          since: 30 Jun 2025 15:06:31Z
        base:
          name: ubuntu
          channel: "22.04"
        constraints: spaces=oam-space
```
